--  See https://wiki.hypr.land/Configuring/Basics/Binds/ for more
local mainMod = ("%s + "):format(require('common').mainMod)
--  Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
hl.bind(mainMod .. "Return", hl.dsp.exec_cmd("uwsm app -- alacritty"))
hl.bind(mainMod .. "SHIFT + C", hl.dsp.window.close())
hl.bind(mainMod .. "C", hl.dsp.exec_cmd("hyprpicker -a"))
hl.bind(mainMod .. "SHIFT + Q", hl.dsp.exit())
hl.bind(mainMod .. "Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. "P", hl.dsp.exec_cmd("~/.config/rofi/launchers/type-1/launcher.sh -run-command uwsm app -- {cmd}"))
hl.bind(mainMod .. "SHIFT + F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. "M", hl.dsp.window.fullscreen())
hl.bind(mainMod .. "SHIFT + P", hl.dsp.window.pin({ action = "toggle" }))
-- hl.bind(mainMod .. "ALT + C", hl.dsp.exec_cmd("~/scripts/toggle_chat_transparency"))
--  Move focus with mainMod + arrow keys
hl.bind(mainMod .. "left", hl.dsp.focus({ direction = "l" }))
hl.bind(mainMod .. "right", hl.dsp.focus({ direction = "r" }))
hl.bind(mainMod .. "up", hl.dsp.focus({ direction = "u" }))
hl.bind(mainMod .. "down", hl.dsp.focus({ direction = "d" }))

hl.bind(mainMod .. "Tab", hl.dsp.focus({ workspace = "previous" }))
hl.bind(mainMod .. "Period", hl.dsp.focus({ workspace = "m+1" }))
hl.bind(mainMod .. "Comma", hl.dsp.focus({ workspace = "m-1" }))
hl.bind(mainMod .. "SHIFT + Period", hl.dsp.window.move({ workspace = "m+1" }))
hl.bind(mainMod .. "SHIFT + Comma", hl.dsp.window.move({ workspace = "m-1" }))
--  Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. "mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind(mainMod .. "mouse:274", hl.dsp.window.close())
--  bind =         , mouse:275, workspace, m-1
--  bind =         , mouse:276, workspace, m+1
hl.bind(mainMod .. "ALT + L", hl.dsp.window.resize({ x = 10,  y = 0,   relative = true }))
hl.bind(mainMod .. "ALT + H", hl.dsp.window.resize({ x = -10, y = 0,   relative = true }))
hl.bind(mainMod .. "ALT + K", hl.dsp.window.resize({ x = 0,   y = -10, relative = true }))
hl.bind(mainMod .. "ALT + J", hl.dsp.window.resize({ x = 0,   y = 10,  relative = true }))
hl.bind(mainMod .. "SHIFT + S", hl.dsp.window.toggle_swallow())
--  General keybinds
hl.bind("Print", hl.dsp.exec_cmd("flameshot gui"))
hl.bind("CONTROL + Print", hl.dsp.exec_cmd("grim -cg $(slurp -ro) - | wl-copy && notify-send Screenshot Screen copied to buffer"))
hl.bind("ALT + Print", hl.dsp.exec_cmd("grim -cg $(~/.config/hypr/selectwindow.sh) - | wl-copy && notify-send Screenshot Window copied to buffer"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("screencast.wayland"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pulsemixer --change-volume +5"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pulsemixer --change-volume -5"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pulsemixer --toggle-mute"))
hl.bind("XF86Tools", hl.dsp.exec_cmd("toggle-tui --option font.size=10 ncmpcpp"))
hl.bind("SHIFT + XF86Tools", hl.dsp.exec_cmd("toggle-window org.pulseaudio.pavucontrol"))
hl.bind("CONTROL + XF86Tools", hl.dsp.exec_cmd("toggle-tui --option font.size=10 btop"))
hl.bind("XF86Calculator", hl.dsp.exec_cmd("toggle-tui + calc -d"))
hl.bind(mainMod .. "E", hl.dsp.exec_cmd("emojis"))
hl.bind(mainMod .. "CONTROL + M", hl.dsp.exec_cmd("manpdf"))
--  Discord binds
-- hl.bind("CONTROL" .. "SHIFT" .. "D")
-- hl.bind("CONTROL" .. "SHIFT" .. "M")
--  Master layout
hl.bind(mainMod .. "SHIFT + Return", hl.dsp.layout("swapwithmaster"))
hl.bind(mainMod .. "J", hl.dsp.layout("cyclenext"))
hl.bind(mainMod .. "K", hl.dsp.layout("cycleprev"))
hl.bind(mainMod .. "SHIFT + J", hl.dsp.layout("swapnext"))
hl.bind(mainMod .. "SHIFT + K", hl.dsp.layout("swapprev"))
hl.bind(mainMod .. "I", hl.dsp.layout("addmaster"))
hl.bind(mainMod .. "D", hl.dsp.layout("removemaster"))
hl.bind(mainMod .. "N", hl.dsp.layout("focusmaster"))
hl.bind(mainMod .. "T", hl.dsp.layout("orientationleft"))
hl.bind(mainMod .. "Y", hl.dsp.layout("orientationtop"))

--  Two monitor setup bindings
hl.bind(mainMod .. "ALT + M", hl.dsp.workspace.swap_monitors({ monitor1 = "current", monitor2 = "+1" }))
hl.bind(mainMod .. "SHIFT + M", hl.dsp.workspace.move({ monitor = "+1" }))
hl.bind(mainMod .. "O", hl.dsp.focus({ monitor = "+1" }))
