#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Get user selection via dmenu from emoji file.
chosen=$(cut -d ';' -f1 ~/scripts/emojis.list | bemenu -i -l 30 -p "Choose an emoji:" | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
	ydotool type "$chosen"
else
	printf "$chosen" | wl-copy
	dunstify "'$chosen' copied to clipboard." &
fi
