#!/usr/bin/env bash

BASE_DIR=~/Videos
OUTPUT_DIR=/tmp/merged

VIDEO_EXTENSIONS=(mkv)
video_name_args=()
for ext in "${VIDEO_EXTENSIONS[@]}"; do
    video_name_args+=(-name "*.$ext" -or)
done
unset "video_name_args[${#name_args[@]}-1]"

SUBDUB_EXTENSIONS=(mka ass)
subdub_name_args=()
for ext in "${SUBDUB_EXTENSIONS[@]}"; do
    subdub_name_args+=(-name "*.$ext" -or)
done
unset "subdub_name_args[${#name_args[@]}-1]"

ALL_EXTEMSIONS=("${VIDEO_EXTENSIONS[@]}" "${SUBDUB_EXTENSIONS[@]}")
name_args=()
for ext in "${ALL_EXTEMSIONS[@]}"; do
    name_args+=(-name "*.$ext" -or)
done
unset "name_args[${#name_args[@]}-1]"

merge() {
    out=$1
    file=$2
    local -n ffmpeg_cmd=$out
    find_args=("$(dirname "$file")" -maxdepth 3 -name "$(printf "%q" "$(basename -s ".${file##*.}" "$file")")*" -and '(')
    find_args+=("${name_args[@]}")
    find_args+=(')')
    readarray -t inputs < <(find "${find_args[@]}" | sort)

    ffmpeg_cmd=(ffmpeg)
    for input in "${inputs[@]}"; do
        ffmpeg_cmd+=(-i "$input")
    done

    ffmpeg_cmd+=(-c copy)

    for ((i = 0; i < ${#inputs[@]}; i++)); do
        ffmpeg_cmd+=(-map "$i")
    done
    out_file="${file/#$BASE_DIR/$OUTPUT_DIR}"
    [[ -d "$(dirname "$out_file")" ]] || mkdir -p "$(dirname "$out_file")"
    ffmpeg_cmd+=("$out_file")
}

merge_many() {
    if [[ ! "$(realpath "$1")" =~ $BASE_DIR/.*/.* ]]; then
        echo "Inappropriate directory."
        return
    fi
    dir="$(realpath "$1")"
    mkdir -p "${dir/#$BASE_DIR/$OUTPUT_DIR}"
    args_dir=$(mktemp -d 'mergevideo_args.XXXXX')
    mkdir "$args_dir/inputs"
    find "$(realpath "$1")" -maxdepth 1 \( "${video_name_args[@]}" \) | sort | sed "s#$BASE_DIR#$OUTPUT_DIR#" > "$args_dir/outputs"
    if [[ "$( (wc -l "$args_dir/outputs" | cut -f1 -d' ') )" -eq 0 ]]; then
        echo "Video files were not found."
        return
    fi

    find "$(realpath "$1")" -maxdepth 1 \( "${video_name_args[@]}" \) | sort > "$args_dir/inputs/0"

    i=1
    find "$1" -maxdepth 3 \
        \( "${subdub_name_args[@]}" \) \
        -printf '%h\n' | uniq | sort | while read -r dir; do
        find "$dir" -maxdepth 1 \( "${name_args[@]}" \) | sort > "$args_dir/inputs/$i"
        ((i++))
    done 
    readarray -t input_idx < <(find "$args_dir/inputs" -type f -printf "%P\n" | sort -n)
    if [[ "${#input_idx[@]}" -lt 2 ]]; then
        echo "External sub and dub files were not found."
        return
    fi
    maps=()
    inputs=()
    input_files=()
    for i in "${input_idx[@]}"; do
        maps+=(-map "$i")
        inputs+=(-i "{$((i+1))}")
        input_files+=('::::+' "$args_dir/inputs/$i")
    done

    parallel --bar ffmpeg -y "${inputs[@]}" -c copy "${maps[@]}" "{$((${#input_idx[@]}+1))}" "${input_files[@]}" ::::+ "$args_dir/outputs"
    rm -rf "$args_dir"
}

if [[ -d "$1" ]]; then
    merge_many "$1"
else
    merge cmd "$(realpath "$1")"
    exec "${cmd[@]}"
fi

