#!/bin/bash

overrides='[
    "Minecraft"
]'

overrides=$(echo "$overrides" | jq -c -c '[.[] | {(.): "NULL"}] | add')

json=$(lutris -loj | jq -c "[.[] | {(.name): .slug}] | add | . + $overrides")

selected=$(echo "$json" | jq -c -r "keys | .[]" | dmenu -l 30 -fn Iosevka:size=20)

if [[ -n "$selected" ]]; then 
    case $selected in
        'Minecraft')
            picomc instance list | dmenu -fn Minecraft:size=35 | xargs -r -Iver picomc instance launch "ver"
            ;;
        *)
            slug=$(echo "$json" | jq -cr ".[\"$selected\"]")
            [[ "$slug" == NULL ]] && notify-send "startgame.sh" "Override hasn't been set for $selected" && exit 1
            lutris "lutris:rungame/$slug"
            ;;
    esac
fi
