#!/usr/bin/env bash

# where music files should go
LIB_DIR=~/EARGASM

url="${1:-$(wl-paste)}"

# get the filename
json=$(yt-dlp --no-warnings -f bestaudio -j "$url" | \
    gojq '{filename, title: (if .track then "\(.uploader | rtrimstr(" - Topic")) - \(.track)" else .title end)}')
[[ -z "$json" ]] && exit 1

file="$(gojq -r '.filename' <<< "$json")"
file=${file%.*}.mp3

# download file (if it is not present)
if [ -f "$file" ]; then 
    echo "File '$file' has already been downloaded"
elif ! yt-dlp -x --audio-format mp3 -f bestaudio "$url"; then
    echo "Error downloaing file from '$1'"
    exit 1
fi

name="$(gojq -r '.title' <<< "$json")"
# asking user if file name is correct
set -o vi
read -i "$name" -p "Enter track name: " -re name
new_file=${name}.mp3
mv "$file" "$new_file"
file=$new_file

# tagging and moving file to library folder
artist=${name%% - *}
song=${name#* - }
id3tag -a"$artist" -s"$song" "$file"
mp3unicode -s utf8 -2 unicode "$file" || echo Something wrong with "$file"
(cd "$LIB_DIR" || exit 1; ls -1dR */) | fzf --filepath-word --prompt="Where to put this song? > " \
    --header-first --header="$artist - $song" | xargs -r -Idir -d \\n mv "$file" "$LIB_DIR/dir"
